### ISSUE TITLE
Built-in snippet still show

### ISSUE THREAD

**Issue by gluons** [svipas/vscode-control-snippets#2]
I try to disable built-in snippet but it doesn't work.  
Disable it then restart 2 times.

**Video:** https://imgur.com/8WjQF8K

Do I use your extension correctly?

**Comment by svipas** [comment]
Hi, seems something wrong because after you pressed OK it should show another page with Reload message. Could you check if after disabling `javascript` and opening <kbd>Control Snippets</kbd> it still shows `javascript` as enabled? Make a video or show me screenshot. It seems like something is wrong with your VS Code, so please provide a version and try to re-install it.

**Comment by gluons** [comment]
> Could you check if after disabling javascript and opening Control Snippets it still shows javascript as enabled?

Yes. It still shows as enabled.

![2019-10-13_17-44-54](https://user-images.githubusercontent.com/4688092/66714477-8a95ac00-ede1-11e9-833e-73a77f2cfa9d.gif)

I've reinstalled extension but it doesn't work. If it's important, I may reinstall VSCode.

**My VSCode version here:**
```
Version: 1.39.1 (system setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by svipas** [comment]
Yeah, seems something is wrong with VS Code or with extension. If you could, please try to re-install VS Code and reply here if it works or no. Also, if it doesn't work after re-install, try to open Developer Tools (`Help -> Toggle Developer Tools`) and see if there's any errors, etc. and copy-paste them here.

**Comment by svipas** [comment]
@gluons Is it working? What happened? Could I close this issue?

**Comment by gluons** [comment]
I'm busy for while. Maybe I'll reinstall VSCode when I'm free at weekend.

**Comment by gluons** [comment]
I've just reinstalled it. It doesn't work at first.  
Then I realize that I'm using **system setup** version.  
So, my VS code is installed in `C:\Program Files`.

Hooray 🎉🎉🎉 I finally found the cause. It's **system setup** version of VS Code.  
So, it requires **Admin Right** to do anything within VS Code directory (that this extension does).

So, I have to **Run VS Code as Admin** before use this extension.

**Comment by gluons** [comment]
PR submitted. Add new FAQ.
