### ISSUE TITLE
there is no ok button

### ISSUE THREAD

**Issue by haifengkao** [svipas/vscode-control-snippets#5]
**Actual**
![截圖 2020-03-03 下午5 33 35](https://user-images.githubusercontent.com/4080524/75762100-1e5a1b80-5d75-11ea-8789-dd834d671343.jpg)

**Expected**
![截圖 2020-03-03 下午5 34 39](https://user-images.githubusercontent.com/4080524/75762235-4fd2e700-5d75-11ea-946d-dad7bccf6657.jpg)

VSCode Version: 1.42.1
Control-Snippets Version: 1.7.4

**Comment by svipas** [comment]
Thanks for report, I also noticed that and seems it's VS Code bug which I guess would be fixed in a next release.

https://github.com/microsoft/vscode/issues/90365
